# -*- coding: utf-8 -*-
"""InternCircle_Task3_Number_Guessing_Word_Counter.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZfoqSakMB9MpccgJ3JUOvuaPnl37hfgY
"""

# ==========================================
# TASK 3: NUMBER GUESSING GAME & WORD COUNTER
# InternCircle
# ==========================================

import random
from collections import Counter


# ==========================================
# PART 1: NUMBER GUESSING GAME
# ==========================================

def number_guessing_game():

    print("\n================================")
    print("       NUMBER GUESSING GAME")
    print("================================")

    # Generate a random number between 1 and 100
    secret_number = random.randint(1, 100)

    attempts = 0
    score = 100

    print("\nI have selected a number between 1 and 100.")
    print("Try to guess the number!")

    while True:

        try:
            guess = int(input("\nEnter your guess: "))
        except ValueError:
            print("Invalid input! Please enter a whole number.")
            continue

        # Check if the number is within the range
        if guess < 1 or guess > 100:
            print("Please enter a number between 1 and 100.")
            continue

        attempts += 1

        # Correct answer
        if guess == secret_number:
            print("\n🎉 Congratulations!")
            print("You guessed the correct number.")
            print("Number of attempts:", attempts)

            # Calculate score
            score = max(10, 100 - ((attempts - 1) * 10))

            print("Your score:", score)
            break

        # Guess is too low
        elif guess < secret_number:
            print("Too low! Try a higher number.")

        # Guess is too high
        else:
            print("Too high! Try a lower number.")


# ==========================================
# PART 2: WORD COUNTER & FREQUENCY ANALYZER
# ==========================================

def word_counter():

    print("\n================================")
    print("     WORD COUNTER & ANALYZER")
    print("================================")

    # Ask user for a text file
    filename = input("\nEnter the text file name: ")

    try:
        # Open and read the file
        with open(filename, "r", encoding="utf-8") as file:
            text = file.read()

        # Convert text to lowercase
        text = text.lower()

        # Remove common punctuation
        punctuation = ".,!?;:\"'()[]{}"

        for symbol in punctuation:
            text = text.replace(symbol, "")

        # Split text into individual words
        words = text.split()

        # Count total words
        total_words = len(words)

        # Count frequency of each word
        word_frequency = Counter(words)

        print("\n---------- RESULTS ----------")

        print("Total number of words:", total_words)

        print("\nWord Frequency:")

        for word, frequency in word_frequency.most_common():
            print(f"{word}: {frequency}")

    except FileNotFoundError:
        print("\nError: File not found!")
        print("Please check the file name and try again.")

    except Exception as error:
        print("\nAn error occurred:", error)


# ==========================================
# MAIN MENU
# ==========================================

def main():

    while True:

        print("\n================================")
        print("       TASK 3 MAIN MENU")
        print("================================")

        print("1. Number Guessing Game")
        print("2. Word Counter & Frequency Analyzer")
        print("3. Exit")

        choice = input("\nEnter your choice (1-3): ")

        if choice == "1":

            number_guessing_game()

        elif choice == "2":

            word_counter()

        elif choice == "3":

            print("\nThank you for using the program!")
            print("Goodbye!")
            break

        else:

            print("\nInvalid choice!")
            print("Please select 1, 2, or 3.")


# ==========================================
# RUN PROGRAM
# ==========================================

main()